version: '3.8'

services:
  loki:
    image: grafana/loki:2.8.6
    container_name: loki
    restart: unless-stopped
    ports:
      - "${LOKI_PORT:-3100}:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml
      - loki_data:/loki
    networks:
      - monitoring

volumes:
  loki_data:

networks:
  monitoring:
    external: true