auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2023-10-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h
        tags:
          source: loki

limits_config:
  retention_period: 720h  # 30 дней
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 дней

chunk_store_config:
  max_look_back_period: 720h

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem