groups:
- name: infra-alerts
  rules:
  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage on {{ $labels.instance }}"
      description: "Memory usage is {{ $value }}%"

  - alert: ContainerDown
    expr: absent(up{job="docker-containers"} == 1)
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Container {{ $labels.container }} is down"
      