version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:2.20.2
    container_name: portainer
    restart: unless-stopped
    ports:
      - "${PORTAINER_PORT:-9000}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - monitoring

volumes:
  portainer_data:

networks:
  monitoring:
    external: true